spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/monolith-ecommerce
spring.datasource.username=postgres
spring.datasource.password=password

#jpa configurations
spring.jpa.show-sql=true

#for creating schemas and tables
spring.jpa.hibernate.ddl-auto=update

#Format SQL queries
spring.jpa.properties.hibernate.format_sql=true